<?php

return [
    [
        'id' => 9001,
        'media_type' => 'movie',
        'title' => 'Интерстеллар',
        'original_title' => 'Interstellar',
        'overview' => 'Команда исследователей отправляется через червоточину, чтобы найти для человечества новый дом.',
        'release_year' => 2014,
        'rating' => 8.7,
        'runtime' => 169,
        'genres' => ['научная фантастика', 'драма', 'приключения'],
        'aliases' => ['interstellar', 'интерстеллар', 'космос', 'нолан'],
    ],
    [
        'id' => 9002,
        'media_type' => 'movie',
        'title' => 'Начало',
        'original_title' => 'Inception',
        'overview' => 'Профессиональный вор проникает в сны и получает задание не украсть идею, а внедрить её.',
        'release_year' => 2010,
        'rating' => 8.8,
        'runtime' => 148,
        'genres' => ['научная фантастика', 'боевик', 'триллер'],
        'aliases' => ['inception', 'начало', 'сон', 'нолан'],
    ],
    [
        'id' => 9003,
        'media_type' => 'movie',
        'title' => 'Матрица',
        'original_title' => 'The Matrix',
        'overview' => 'Хакер узнаёт, что привычный мир — это симуляция, а человечество живёт под контролем машин.',
        'release_year' => 1999,
        'rating' => 8.7,
        'runtime' => 136,
        'genres' => ['научная фантастика', 'боевик'],
        'aliases' => ['matrix', 'матрица', 'нео', 'киберпанк'],
    ],
    [
        'id' => 9004,
        'media_type' => 'movie',
        'title' => 'Прибытие',
        'original_title' => 'Arrival',
        'overview' => 'Лингвист пытается понять язык пришельцев, от которого зависит судьба всего мира.',
        'release_year' => 2016,
        'rating' => 7.9,
        'runtime' => 116,
        'genres' => ['научная фантастика', 'драма', 'детектив'],
        'aliases' => ['arrival', 'прибытие', 'пришельцы', 'язык'],
    ],
    [
        'id' => 9005,
        'media_type' => 'movie',
        'title' => 'Дюна',
        'original_title' => 'Dune',
        'overview' => 'Наследник великого дома оказывается в центре борьбы за самую ценную субстанцию во Вселенной.',
        'release_year' => 2021,
        'rating' => 8.0,
        'runtime' => 155,
        'genres' => ['научная фантастика', 'приключения', 'драма'],
        'aliases' => ['dune', 'дюна', 'арракис', 'пол атрейдес'],
    ],
    [
        'id' => 9006,
        'media_type' => 'movie',
        'title' => 'Бегущий по лезвию 2049',
        'original_title' => 'Blade Runner 2049',
        'overview' => 'Репликант-офицер раскрывает тайну, способную разрушить остатки мира будущего.',
        'release_year' => 2017,
        'rating' => 8.0,
        'runtime' => 164,
        'genres' => ['научная фантастика', 'триллер', 'драма'],
        'aliases' => ['blade runner 2049', 'бегущий по лезвию', '2049', 'киберпанк'],
    ],
    [
        'id' => 9007,
        'media_type' => 'movie',
        'title' => 'Тёмный рыцарь',
        'original_title' => 'The Dark Knight',
        'overview' => 'Бэтмен пытается остановить Джокера, который превращает Готэм в арену морального хаоса.',
        'release_year' => 2008,
        'rating' => 9.0,
        'runtime' => 152,
        'genres' => ['боевик', 'криминал', 'драма'],
        'aliases' => ['dark knight', 'тёмный рыцарь', 'джокер', 'бетмен'],
    ],
    [
        'id' => 9008,
        'media_type' => 'movie',
        'title' => 'Побег из Шоушенка',
        'original_title' => 'The Shawshank Redemption',
        'overview' => 'Несправедливо осуждённый банкир строит надежду и дружбу внутри суровой тюремной системы.',
        'release_year' => 1994,
        'rating' => 9.3,
        'runtime' => 142,
        'genres' => ['драма'],
        'aliases' => ['shawshank', 'побег из шоушенка', 'тюрьма'],
    ],
    [
        'id' => 9009,
        'media_type' => 'movie',
        'title' => 'Паразиты',
        'original_title' => 'Parasite',
        'overview' => 'Бедная семья постепенно внедряется в жизнь богатого дома, и всё выходит из-под контроля.',
        'release_year' => 2019,
        'rating' => 8.5,
        'runtime' => 132,
        'genres' => ['триллер', 'драма', 'комедия'],
        'aliases' => ['parasite', 'паразиты', 'корея'],
    ],
    [
        'id' => 9010,
        'media_type' => 'movie',
        'title' => 'Поезд в Пусан',
        'original_title' => 'Train to Busan',
        'overview' => 'Пассажиры скоростного поезда пытаются выжить во время внезапной зомби-эпидемии.',
        'release_year' => 2016,
        'rating' => 7.6,
        'runtime' => 118,
        'genres' => ['ужасы', 'боевик', 'триллер'],
        'aliases' => ['train to busan', 'поезд в пусан', 'зомби', 'корея'],
    ],
    [
        'id' => 9011,
        'media_type' => 'movie',
        'title' => 'Помни',
        'original_title' => 'Memento',
        'overview' => 'Мужчина с потерей кратковременной памяти пытается восстановить цепочку событий и найти убийцу жены.',
        'release_year' => 2000,
        'rating' => 8.4,
        'runtime' => 113,
        'genres' => ['триллер', 'детектив'],
        'aliases' => ['memento', 'помни', 'память', 'нолан'],
    ],
    [
        'id' => 9012,
        'media_type' => 'movie',
        'title' => 'Одержимость',
        'original_title' => 'Whiplash',
        'overview' => 'Молодой барабанщик сталкивается с безжалостным наставником и ставит карьеру выше всего.',
        'release_year' => 2014,
        'rating' => 8.5,
        'runtime' => 106,
        'genres' => ['драма', 'музыка'],
        'aliases' => ['whiplash', 'одержимость', 'джаз', 'барабан'],
    ],
    [
        'id' => 9013,
        'media_type' => 'movie',
        'title' => 'Ла-Ла Ленд',
        'original_title' => 'La La Land',
        'overview' => 'Музыкант и актриса влюбляются в Лос-Анджелесе, пытаясь не потерять мечты и друг друга.',
        'release_year' => 2016,
        'rating' => 8.0,
        'runtime' => 128,
        'genres' => ['мелодрама', 'драма', 'музыка'],
        'aliases' => ['la la land', 'ла-ла ленд', 'мюзикл'],
    ],
    [
        'id' => 9014,
        'media_type' => 'movie',
        'title' => 'Властелин колец: Братство кольца',
        'original_title' => 'The Lord of the Rings: The Fellowship of the Ring',
        'overview' => 'Хоббиту Фродо предстоит покинуть дом и отправиться в путешествие, чтобы уничтожить Кольцо Всевластия.',
        'release_year' => 2001,
        'rating' => 8.8,
        'runtime' => 178,
        'genres' => ['фэнтези', 'приключения', 'драма'],
        'aliases' => ['lord of the rings', 'братство кольца', 'властелин колец', 'фэнтези'],
    ],
    [
        'id' => 9015,
        'media_type' => 'movie',
        'title' => 'Человек-паук: Через вселенные',
        'original_title' => 'Spider-Man: Into the Spider-Verse',
        'overview' => 'Майлз Моралес встречает других версий Человека-паука и спасает мультивселенную.',
        'release_year' => 2018,
        'rating' => 8.4,
        'runtime' => 117,
        'genres' => ['мультфильм', 'боевик', 'приключения'],
        'aliases' => ['spider-verse', 'через вселенные', 'майлз', 'spider man', 'мультфильм'],
    ],
    [
        'id' => 9016,
        'media_type' => 'movie',
        'title' => 'После Янга',
        'original_title' => 'After Yang',
        'overview' => 'Семья пытается восстановить андроида-компаньона и обнаруживает в нём следы собственной истории.',
        'release_year' => 2021,
        'rating' => 6.7,
        'runtime' => 96,
        'genres' => ['научная фантастика', 'драма'],
        'aliases' => ['after yang', 'после янга', 'андроид'],
    ],
    [
        'id' => 9017,
        'media_type' => 'movie',
        'title' => 'Всё везде и сразу',
        'original_title' => 'Everything Everywhere All at Once',
        'overview' => 'Обычная женщина внезапно оказывается единственным человеком, способным остановить хаос мультивселенной.',
        'release_year' => 2022,
        'rating' => 7.8,
        'runtime' => 139,
        'genres' => ['фантастика', 'боевик', 'комедия'],
        'aliases' => ['everything everywhere all at once', 'всё везде и сразу', 'мультивселенная'],
    ],
    [
        'id' => 9018,
        'media_type' => 'movie',
        'title' => 'Поймай меня, если сможешь',
        'original_title' => 'Catch Me If You Can',
        'overview' => 'Юный мошенник выдаёт себя за пилота, врача и юриста, пока агент ФБР идёт по его следу.',
        'release_year' => 2002,
        'rating' => 8.1,
        'runtime' => 141,
        'genres' => ['криминал', 'драма'],
        'aliases' => ['catch me if you can', 'поймай меня если сможешь', 'мошенник'],
    ],
    [
        'id' => 9101,
        'media_type' => 'tv',
        'title' => 'Во все тяжкие',
        'original_title' => 'Breaking Bad',
        'overview' => 'Учитель химии узнаёт о болезни и начинает производить метамфетамин, втягивая семью в опасную двойную жизнь.',
        'release_year' => 2008,
        'rating' => 9.5,
        'runtime' => 49,
        'genres' => ['драма', 'криминал', 'триллер'],
        'aliases' => ['breaking bad', 'во все тяжкие', 'уолтер уайт', 'сериал'],
    ],
    [
        'id' => 9102,
        'media_type' => 'tv',
        'title' => 'Аркейн',
        'original_title' => 'Arcane',
        'overview' => 'История сестёр Вай и Джинкс на фоне конфликта между процветающим Пилтовером и мрачным Зауном.',
        'release_year' => 2021,
        'rating' => 9.0,
        'runtime' => 41,
        'genres' => ['анимация', 'фэнтези', 'боевик'],
        'aliases' => ['arcane', 'аркейн', 'league of legends', 'мультсериал', 'анимация'],
    ],
    [
        'id' => 9103,
        'media_type' => 'tv',
        'title' => 'Атака титанов',
        'original_title' => 'Attack on Titan',
        'overview' => 'Человечество сражается за выживание за стенами, пока Эрен открывает страшную правду о титанах и мире.',
        'release_year' => 2013,
        'rating' => 9.0,
        'runtime' => 24,
        'genres' => ['аниме', 'боевик', 'драма'],
        'aliases' => ['attack on titan', 'shingeki no kyojin', 'атака титанов', 'аниме'],
    ],
    [
        'id' => 9104,
        'media_type' => 'tv',
        'title' => 'Тетрадь смерти',
        'original_title' => 'Death Note',
        'overview' => 'Старшеклассник получает тетрадь, способную убивать по имени, и начинает опасную игру с гениальным детективом.',
        'release_year' => 2006,
        'rating' => 8.9,
        'runtime' => 23,
        'genres' => ['аниме', 'триллер', 'детектив'],
        'aliases' => ['death note', 'тетрадь смерти', 'аниме', 'л'],
    ],
    [
        'id' => 9105,
        'media_type' => 'tv',
        'title' => 'Провожающая в последний путь Фрирен',
        'original_title' => 'Frieren: Beyond Journey\'s End',
        'overview' => 'Эльфийка-маг спустя десятилетия после победы над злом пытается понять ценность времени, дружбы и человеческой жизни.',
        'release_year' => 2023,
        'rating' => 8.9,
        'runtime' => 24,
        'genres' => ['аниме', 'фэнтези', 'драма'],
        'aliases' => ['frieren', 'фрирен', 'провожающая в последний путь', 'аниме', 'фэнтези'],
    ],
    [
        'id' => 9106,
        'media_type' => 'tv',
        'title' => 'Истребитель демонов',
        'original_title' => 'Demon Slayer: Kimetsu no Yaiba',
        'overview' => 'Юноша становится охотником на демонов после трагедии в семье и ищет способ вернуть сестре человеческий облик.',
        'release_year' => 2019,
        'rating' => 8.6,
        'runtime' => 24,
        'genres' => ['аниме', 'боевик', 'фэнтези'],
        'aliases' => ['demon slayer', 'kimetsu no yaiba', 'истребитель демонов', 'аниме'],
    ],
    [
        'id' => 9107,
        'media_type' => 'tv',
        'title' => 'Истинная красота',
        'original_title' => 'True Beauty',
        'overview' => 'Школьница, скрывающая неуверенность за мастерством макияжа, оказывается в центре романтического треугольника.',
        'release_year' => 2020,
        'rating' => 8.3,
        'runtime' => 70,
        'genres' => ['дорама', 'мелодрама', 'комедия'],
        'aliases' => ['true beauty', 'истинная красота', 'дорама', 'корейский сериал'],
    ],
    [
        'id' => 9108,
        'media_type' => 'tv',
        'title' => 'Аварийная посадка любви',
        'original_title' => 'Crash Landing on You',
        'overview' => 'Южнокорейская наследница случайно оказывается в Северной Корее и встречает офицера, который решает помочь ей вернуться домой.',
        'release_year' => 2019,
        'rating' => 8.7,
        'runtime' => 76,
        'genres' => ['дорама', 'мелодрама', 'драма'],
        'aliases' => ['crash landing on you', 'аварийная посадка любви', 'дорама', 'корея'],
    ],
    [
        'id' => 9109,
        'media_type' => 'tv',
        'title' => 'Необычный адвокат У Ён У',
        'original_title' => 'Extraordinary Attorney Woo',
        'overview' => 'Талантливая девушка с аутизмом начинает карьеру в крупной юридической фирме и меняет представление окружающих о норме.',
        'release_year' => 2022,
        'rating' => 8.6,
        'runtime' => 70,
        'genres' => ['дорама', 'драма', 'комедия'],
        'aliases' => ['attorney woo', 'extraordinary attorney woo', 'у ён у', 'дорама'],
    ],
    [
        'id' => 9110,
        'media_type' => 'tv',
        'title' => 'Аватар: Легенда об Аанге',
        'original_title' => 'Avatar: The Last Airbender',
        'overview' => 'Юный аватар учится управлять стихиями, чтобы остановить Страну Огня и восстановить баланс в мире.',
        'release_year' => 2005,
        'rating' => 9.3,
        'runtime' => 24,
        'genres' => ['мультсериал', 'приключения', 'фэнтези'],
        'aliases' => ['avatar the last airbender', 'аватар аанга', 'мультсериал', 'анимация'],
    ],
    [
        'id' => 9111,
        'media_type' => 'tv',
        'title' => 'Рик и Морти',
        'original_title' => 'Rick and Morty',
        'overview' => 'Гениальный и безумный учёный вместе с внуком путешествует по мультивселенной и вечно вляпывается в абсурдные приключения.',
        'release_year' => 2013,
        'rating' => 8.7,
        'runtime' => 22,
        'genres' => ['мультсериал', 'комедия', 'фантастика'],
        'aliases' => ['rick and morty', 'рик и морти', 'мультсериал', 'фантастика'],
    ],
    [
        'id' => 9112,
        'media_type' => 'tv',
        'title' => 'Синий глаз самурая',
        'original_title' => 'Blue Eye Samurai',
        'overview' => 'Воин скрывает своё происхождение и отправляется в кровавый путь мести по Японии периода Эдо.',
        'release_year' => 2023,
        'rating' => 8.7,
        'runtime' => 48,
        'genres' => ['анимация', 'боевик', 'драма'],
        'aliases' => ['blue eye samurai', 'синий глаз самурая', 'анимация', 'мультсериал'],
    ],
];
